### ISSUE TITLE
Add graphics to hero space

### ISSUE THREAD

**Issue by joestemarie** [lelafeldmeier/SLS2015#1]

**Comment by lelafeldmeier** [comment]
Slider (?)

**Comment by joestemarie** [comment]
Or you could even do some kind of parallax. Doesn't have to be crazy.

**Comment by lelafeldmeier** [comment]
In a perfect header world: http://2014.designweekportland.com/

**Comment by joestemarie** [comment]
Can we just steal that code?

**Comment by joestemarie** [comment]
Is that like _legal or whatever_

**Comment by joestemarie** [comment]
Should be pretty easy to just set a variable equal to scroll position and then cycle through a list of images?
